---
version: '3.7'
services:
  cal:
    build: prog
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: mydata
        target: ./tmp/calculator-servlet-example/target/mycalcwebapp.war 
         