---
version: '3.7'
services:
  cal:
    build: prog
    ports:
      - "8080:8080"
    volumes:
      - ./data:/tmp/calculator-servlet-example/target/

  alp:      
    build: alp
    ports:
      - "8070:8080"
    volumes:
      - ./data:/tmp/dta

volumes:
 cal:
 alp: