---
version: '3.7'
services:
  cal:
    build: prog
    ports:
      - "8079:8080"
    volumes:
      - ./data:/home/tomcat/apache-tomcat-9.0.10/webapps/

  alp:      
    build: alp
    ports:
      - "8081:8080"
    #volumes:
     # - ./data:/home/tomcat/apache-tomcat-9.0.10/webapps/mycalcwebapp.war
    depends_on:
      - cal

volumes:
 cal:
 alp: