---
version: '3.7'
services:
  cal:
    build: prog
    ports:
      - "8079:8080"
    volumes:
      - ./data:/opt/tomcat/webapps/

  alp:      
    build: alp
    ports:
      - "8081:8080"
    volumes:
      - ./data:/opt/tomcat/webapps/
    depends_on:
      - cal

volumes:
 cal:
 alp: