---
version: '3.7'
services:
  cal:
    build: prog
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: mydata
        target: /data:/tmp/calculator-servlet-example/target/

  alp:      
    build: alp
    ports:
      - "8070:8080"
    volumes:
    - type: volume 
      source: mydata
      target: /data:/tmp/dta

volumes:
 mydata