---
version: '3.7'
services:
  cal:
    build: prog
    ports:
      - "8079:8080"
    volumes:
      - ./data:/tmp/calculator-servlet-example/target/mycalcwebapp.war 

  alp:      
    build: alp
    ports:
      - "8081:8080"
    volumes:
      - ./data:/usr/local/tomcat/webapps/ 
    depends_on:
      - cal

volumes:
 cal:
 alp: